name: publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', 'gradle/**') }}
          restore-keys: -${{ runner.os }}-gradle-
      - name: Publish artifacts
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubActor: ${{ env.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Configures gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: equidis
          service_account_key: ${{ secrets.GCP_GCR_SECRET }}
      - name: Authenticate to GCR
        run: gcloud auth configure-docker
      - name: Publish Docker image
        run: ./gradlew jib
